/**
 * The document loaded into Code Lab's "Web (HTML/CSS/JS)" preview iframe.
 *
 * Security model (the page itself has no secrets to leak, but we still treat
 * the learner's code as hostile):
 *  - the iframe is `sandbox="allow-scripts"` only: opaque origin, so no access
 *    to this site's localStorage/cookies/JWT, no top navigation, no popups, no forms;
 *  - this document starts with a strict CSP <meta>: no network at all (fetch,
 *    XHR, WebSocket, external scripts/styles/frames); only inline code and
 *    data:/blob: images, fonts and media;
 *  - a tiny harness (installed before any user script) mirrors console output
 *    and uncaught errors to the parent over postMessage, with a size cap.
 *
 * Pure string building so it can be unit-tested without a browser.
 */

export const WEB_PREVIEW_CSP = [
  "default-src 'none'",
  "script-src 'unsafe-inline' 'unsafe-eval'",
  "style-src 'unsafe-inline'",
  "img-src data: blob:",
  "font-src data:",
  "media-src data: blob:",
  "base-uri 'none'",
  "form-action 'none'",
].join("; ");

export interface WebHarnessLimits {
  /** Characters of console output forwarded to the parent. */
  keepChars: number;
}

export const WEB_LIMITS: WebHarnessLimits = { keepChars: 64 * 1024 };

/** Messages the harness sends to the parent. `k` is the per-run token. */
export type WebMessage =
  | { imb: string; t: "log"; level: "log" | "warn" | "error"; text: string }
  | { imb: string; t: "error"; message: string; line?: number; col?: number }
  | { imb: string; t: "done" };

function harness(token: string, keepChars: number): string {
  // The token is generated by us ([a-z0-9] only) but is still JSON-encoded.
  const t = JSON.stringify(token);
  // One line on purpose: injecting it into the user's <head> line must not shift
  // the line numbers of their own scripts in error reports.
  const body = [
    `var T=${t},CAP=${keepChars},sent=0;`,
    `function send(m){m.imb=T;try{parent.postMessage(m,"*")}catch(e){}}`,
    `function fmt(a){return Array.prototype.map.call(a,function(x){`,
    `if(typeof x==="string")return x;`,
    `if(x instanceof Error)return x.stack||x.name+": "+x.message;`,
    `if(typeof x==="object"&&x!==null){try{return JSON.stringify(x)}catch(e){return String(x)}}`,
    `return String(x)}).join(" ")}`,
    `["log","info","debug","warn","error"].forEach(function(l){`,
    `var level=l==="warn"?"warn":l==="error"?"error":"log";var orig=console[l];`,
    `console[l]=function(){var text=fmt(arguments);`,
    `if(sent<CAP){var part=text.length>CAP-sent?text.slice(0,CAP-sent):text;sent+=part.length+1;send({t:"log",level:level,text:part})}`,
    `try{orig.apply(console,arguments)}catch(e){}}});`,
    `window.addEventListener("error",function(e){send({t:"error",message:String(e.message||"Script error"),line:e.lineno||undefined,col:e.colno||undefined})});`,
    `window.addEventListener("unhandledrejection",function(e){var r=e.reason;send({t:"error",message:"Unhandled promise rejection: "+(r&&r.message?r.message:String(r))})});`,
    `window.addEventListener("load",function(){setTimeout(function(){send({t:"done"})},50)});`,
  ].join("");
  return `<script>(function(){${body}})();<\/script>`;
}

/**
 * Builds the srcdoc for `code` (a full document or just a fragment). The CSP
 * meta and harness are placed first so nothing in the user's markup runs before them.
 */
export function buildPreviewDocument(code: string, token: string, limits: WebHarnessLimits = WEB_LIMITS): string {
  const inject = `<meta http-equiv="Content-Security-Policy" content="${WEB_PREVIEW_CSP}">${harness(token, limits.keepChars)}`;

  const head = code.match(/<head(\s[^>]*)?>/i);
  if (head && head.index !== undefined) {
    const at = head.index + head[0].length;
    return code.slice(0, at) + inject + code.slice(at);
  }
  const htmlTag = code.match(/<html(\s[^>]*)?>/i);
  if (htmlTag && htmlTag.index !== undefined) {
    const at = htmlTag.index + htmlTag[0].length;
    return `${code.slice(0, at)}<head><meta charset="utf-8">${inject}</head>${code.slice(at)}`;
  }
  // A fragment (or text before any tag): wrap it in a standards-mode document.
  return `<!doctype html><html><head><meta charset="utf-8">${inject}</head><body>${code}</body></html>`;
}

/** Validates an untrusted postMessage payload against the run's token. */
export function parseWebMessage(data: unknown, token: string): WebMessage | null {
  if (!data || typeof data !== "object") return null;
  const m = data as Record<string, unknown>;
  if (m.imb !== token) return null;
  if (m.t === "done") return { imb: token, t: "done" };
  if (m.t === "log" && typeof m.text === "string") {
    const level = m.level === "warn" || m.level === "error" ? m.level : "log";
    return { imb: token, t: "log", level, text: m.text };
  }
  if (m.t === "error" && typeof m.message === "string") {
    return {
      imb: token,
      t: "error",
      message: m.message,
      line: typeof m.line === "number" ? m.line : undefined,
      col: typeof m.col === "number" ? m.col : undefined,
    };
  }
  return null;
}
