/**
 * The document loaded into Code Lab's "Web (HTML/CSS/JS)" preview iframe.
 *
 * Security model (the page itself has no secrets to leak, but we still treat
 * the learner's code as hostile):
 *  - the iframe is `sandbox="allow-scripts"` only: opaque origin, so no access
 *    to this site's localStorage/cookies/JWT, no top navigation, no popups, no forms;
 *  - this document starts with a strict CSP <meta>: no network at all (fetch,
 *    XHR, WebSocket, external scripts/styles/frames); only inline code and
 *    data:/blob: images, fonts and media;
 *  - a tiny harness (installed before any user script) mirrors console output
 *    and uncaught errors to the parent over postMessage, with a size cap;
 *  - the harness also defines the run's loop guard (see loop-guard.ts), which
 *    stops a runaway loop inside the frame where the parent's watchdog cannot.
 *
 * Pure string building so it can be unit-tested without a browser.
 */

export const WEB_PREVIEW_CSP = [
  "default-src 'none'",
  "script-src 'unsafe-inline' 'unsafe-eval'",
  "style-src 'unsafe-inline'",
  "img-src data: blob:",
  "font-src data:",
  "media-src data: blob:",
  "base-uri 'none'",
  "form-action 'none'",
].join("; ");

export interface WebHarnessLimits {
  /** Characters of console output forwarded to the parent. */
  keepChars: number;
  /**
   * How long the page may stay busy in loops without returning to the event loop
   * before the loop guard stops it. The runner passes its watchdog limit here.
   */
  loopMs: number;
}

export const WEB_LIMITS: WebHarnessLimits = { keepChars: 64 * 1024, loopMs: 5_000 };

/** Messages the harness sends to the parent. `imb` is the per-run token. */
export type WebMessage =
  | { imb: string; t: "log"; level: "log" | "warn" | "error"; text: string }
  | { imb: string; t: "error"; message: string; line?: number; col?: number }
  /** The loop guard stopped a loop that kept the page busy for longer than `loopMs`. */
  | { imb: string; t: "loop"; line?: number }
  | { imb: string; t: "done" };

/**
 * The global function, unique to this run, that guarded loops call (see loop-guard.ts).
 * The suffix comes from the run token, so learner code cannot collide with it by accident.
 */
export function loopGuardName(token: string): string {
  return `__imbLoop_${token.replace(/[^A-Za-z0-9]/g, "").slice(0, 16)}`;
}

/**
 * The loop guard. `g(line)` is called at the top of every loop body. It reads the
 * clock on an adaptive stride (every call while iterations are slow, up to every
 * 1024th while they are fast) and throws once the page has been busy for more than
 * `loopMs` since its first check in this stretch. A message on a private
 * MessageChannel, which is a task and so only arrives once the page returns to the
 * event loop, starts a new stretch. Not a timer: the page can clear timers (a
 * "clear every timer" loop would leave the stretch open forever, so every later
 * loop would be stopped at once) and browsers throttle them (a hidden tab's idle
 * time would count as busy time). Microtasks are not tasks, so a loop that only
 * awaits promises is still stopped. Browsers without MessageChannel fall back to a
 * timer. ES5, one line (see `harness`).
 */
function loopGuard(name: string, loopMs: number): string {
  return [
    `var P=window.performance,PN=P&&P.now,DN=Date.now,LIM=${loopMs};`,
    `var now=PN?function(){return PN.call(P)}:function(){return DN.call(Date)};`,
    `var k=0,stride=1,since=0,last=0,armed=false,told=false;`,
    `function idle(){armed=false;k=0}`,
    `var tick,MC=window.MessageChannel;`,
    `try{var mc=new MC();mc.port1.onmessage=idle;tick=mc.port2.postMessage.bind(mc.port2,0)}`,
    `catch(e){var ST=setTimeout;tick=function(){ST(idle,0)}}`,
    `function g(l){if(--k>0)return;var n=now();`,
    `if(!armed){armed=true;told=false;since=last=n;stride=1;tick()}`,
    `else{stride=n-last<2?Math.min(stride*2,1024):1;last=n}`,
    `k=stride;`,
    `if(n-since>LIM){k=0;if(!told){told=true;send({t:"loop",line:l})}`,
    `throw new RangeError("Code Lab stopped a loop that ran longer than "+LIM/1000+" s (line "+l+")")}}`,
    `try{Object.defineProperty(window,${JSON.stringify(name)},{value:g})}catch(e){}`,
  ].join("");
}

function harness(token: string, limits: WebHarnessLimits): string {
  const { keepChars, loopMs } = limits;
  // The token is generated by us ([a-z0-9] only) but is still JSON-encoded.
  const t = JSON.stringify(token);
  // One line on purpose: injecting it into the user's <head> line must not shift
  // the line numbers of their own scripts in error reports.
  const body = [
    `var T=${t},CAP=${keepChars},sent=0;`,
    `function send(m){m.imb=T;try{parent.postMessage(m,"*")}catch(e){}}`,
    `function fmt(a){return Array.prototype.map.call(a,function(x){`,
    `if(typeof x==="string")return x;`,
    `if(x instanceof Error)return x.stack||x.name+": "+x.message;`,
    `if(typeof x==="object"&&x!==null){try{return JSON.stringify(x)}catch(e){return String(x)}}`,
    `return String(x)}).join(" ")}`,
    `["log","info","debug","warn","error"].forEach(function(l){`,
    `var level=l==="warn"?"warn":l==="error"?"error":"log";var orig=console[l];`,
    `console[l]=function(){var text=fmt(arguments);`,
    `if(sent<CAP){var part=text.length>CAP-sent?text.slice(0,CAP-sent):text;sent+=part.length+1;send({t:"log",level:level,text:part})}`,
    `try{orig.apply(console,arguments)}catch(e){}}});`,
    `window.addEventListener("error",function(e){send({t:"error",message:String(e.message||"Script error"),line:e.lineno||undefined,col:e.colno||undefined})});`,
    `window.addEventListener("unhandledrejection",function(e){var r=e.reason;send({t:"error",message:"Unhandled promise rejection: "+(r&&r.message?r.message:String(r))})});`,
    `window.addEventListener("load",function(){setTimeout(function(){send({t:"done"})},50)});`,
    loopGuard(loopGuardName(token), loopMs),
  ].join("");
  return `<script>(function(){${body}})();<\/script>`;
}

/**
 * Builds the srcdoc for `code` (a full document or just a fragment). The CSP
 * meta and harness are placed first so nothing in the user's markup runs before them.
 */
export function buildPreviewDocument(code: string, token: string, limits: WebHarnessLimits = WEB_LIMITS): string {
  const inject = `<meta http-equiv="Content-Security-Policy" content="${WEB_PREVIEW_CSP}">${harness(token, limits)}`;

  const head = code.match(/<head(\s[^>]*)?>/i);
  if (head && head.index !== undefined) {
    const at = head.index + head[0].length;
    return code.slice(0, at) + inject + code.slice(at);
  }
  const htmlTag = code.match(/<html(\s[^>]*)?>/i);
  if (htmlTag && htmlTag.index !== undefined) {
    const at = htmlTag.index + htmlTag[0].length;
    return `${code.slice(0, at)}<head><meta charset="utf-8">${inject}</head>${code.slice(at)}`;
  }
  // A fragment (or text before any tag): wrap it in a standards-mode document.
  return `<!doctype html><html><head><meta charset="utf-8">${inject}</head><body>${code}</body></html>`;
}

/** Validates an untrusted postMessage payload against the run's token. */
export function parseWebMessage(data: unknown, token: string): WebMessage | null {
  if (!data || typeof data !== "object") return null;
  const m = data as Record<string, unknown>;
  if (m.imb !== token) return null;
  if (m.t === "done") return { imb: token, t: "done" };
  if (m.t === "loop") return { imb: token, t: "loop", line: typeof m.line === "number" && m.line > 0 ? m.line : undefined };
  if (m.t === "log" && typeof m.text === "string") {
    const level = m.level === "warn" || m.level === "error" ? m.level : "log";
    return { imb: token, t: "log", level, text: m.text };
  }
  if (m.t === "error" && typeof m.message === "string") {
    return {
      imb: token,
      t: "error",
      message: m.message,
      line: typeof m.line === "number" ? m.line : undefined,
      col: typeof m.col === "number" ? m.col : undefined,
    };
  }
  return null;
}
