/**
 * Generates worker/src/generated/catalog.ts from the canonical course data.
 *
 *   npm run gen:catalog     write the file
 *   npm run check:catalog   exit 1 if the committed file is stale (CI)
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { roadmaps } from "../data/roadmaps";
import { courses } from "../lib/catalog";
import { loadLesson } from "../data/lessons";
import type { Catalog, CatalogLab, CatalogTrack } from "../shared/catalog";

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), "../worker/src/generated/catalog.ts");

async function build(): Promise<Catalog> {
  const tracks: CatalogTrack[] = [];
  const labs: CatalogLab[] = [];
  for (const r of roadmaps) {
    const course = courses.find((c) => c.id === r.id);
    const lessonIds: string[] = [];
    for (const ref of course?.lessons ?? []) {
      const lesson = await loadLesson(r.id, ref.lessonId);
      if (!lesson) continue;
      lessonIds.push(ref.lessonId);
      for (const s of lesson.sections) {
        if (s.type !== "lab") continue;
        labs.push({
          ref: `${r.id}/${ref.lessonId}/${s.id}`,
          track: r.id,
          lesson: ref.lessonId,
          id: s.id,
          lang: s.lang,
          tests: s.tests.map((t) => ({
            name: t.name.en,
            stdin: t.stdin ?? "",
            expected: t.expected,
            mode: t.mode ?? "trim",
            ...(t.epsilon !== undefined ? { epsilon: t.epsilon } : {}),
          })),
        });
      }
    }
    tracks.push({ id: r.id, title: r.title, lessons: lessonIds });
  }
  const refs = new Set<string>();
  for (const l of labs) {
    if (refs.has(l.ref)) throw new Error(`Duplicate lab exercise ref: ${l.ref}`);
    refs.add(l.ref);
  }
  return { tracks, labs };
}

const header = `// GENERATED by scripts/gen-catalog.mts from data/** — do not edit by hand.\n// Regenerate with: npm run gen:catalog   (CI runs: npm run check:catalog)\nimport type { Catalog } from "../../../shared/catalog";\n\n`;

const catalog = await build();
const text = `${header}export const catalog: Catalog = ${JSON.stringify(catalog, null, 2)};\n`;

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== text) {
    console.error("worker/src/generated/catalog.ts is stale. Run: npm run gen:catalog");
    process.exit(1);
  }
  console.log(`catalog up to date (${catalog.tracks.length} tracks, ${catalog.labs.length} lab exercises)`);
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT} (${catalog.tracks.length} tracks, ${catalog.labs.length} lab exercises)`);
}
